/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wuvynyiopwzwtesbiojf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dnlueWlvcHd6d3Rlc2Jpb2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzY3NDIsImV4cCI6MjA3Nzc1Mjc0Mn0.wbdMTLrio7sMdbF0zZMDYtOJ-h85wkYNr9f90OYCdJI"

export default {
  SUPABASE_PROJECT_ID: projectId,
  SUPABASE_PUBLIC_ANON_KEY: publicAnonKey
}
