/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mzdzsbruyisqwcqezjfv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZHpzYnJ1eWlzcXdjcWV6amZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODU3MDQsImV4cCI6MjA3ODM2MTcwNH0.jmqcFA0D4gphFRLGXfyoOU9E9S6vo4DHPWf-Q_oUMPY"

export default {
  SUPABASE_PROJECT_ID: projectId,
  SUPABASE_PUBLIC_ANON_KEY: publicAnonKey
}
